### ISSUE TITLE
Heightmap gets flipped on output

### ISSUE THREAD

**Issue by Russlyman** [laurirasanen/Shovel#1]
The exported vmap file is flipped compared to the imported heightmap. I have uploaded a photo of the Hammer view and a screenshot of the heightmap bmp (can't upload here due to file extension restrictions).

![heightmap](https://user-images.githubusercontent.com/10534452/117195441-2e3c1800-addd-11eb-9e45-d9d0e5c8b2db.png)
![hammer](https://user-images.githubusercontent.com/10534452/117195549-4dd34080-addd-11eb-9a61-e3f40d7def24.png)

**Comment by laurirasanen** [comment]
It looks like just the Y-axis of the heightmap is getting flipped. The initial camera position in the vmap is also oriented in the opposite direction of what you'd expect.
Both problems should be fixed in the latest release, feel free to reopen the issue if not.
